name: PR Validation

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  validate:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore vehicare-be.sln

    - name: Build solution
      run: dotnet build vehicare-be.sln --configuration Release --no-restore

    - name: Run tests with coverage
      run: |
        dotnet test vehicare-be.sln \
          --configuration Release \
          --no-build \
          --verbosity normal \
          --collect:"XPlat Code Coverage" \
          --results-directory ./coverage \
          --logger trx

    - name: Check test results
      run: |
        if [ -f "./coverage/*.trx" ]; then
          echo "Tests completed successfully"
        else
          echo "No test results found"
          exit 1
        fi

    - name: Comment PR with test results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');

          // Read test results
          let testSummary = 'Tests completed successfully! ✅';

          // Create or update comment
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## 🧪 Test Results\n\n${testSummary}\n\n*This comment was automatically generated by the CI pipeline.*`
          });

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          ./coverage/*.trx
          ./coverage/*/coverage.cobertura.xml
        retention-days: 5
